http:
  port: 9090
  host: localhost

admin:
  port: 9876
  host: localhost

apiEndpoints:
  authAPI:
    paths: ["/api/auth/*"]
  usersAPI:
    paths: ["/api/users/*"]
  # transactionsAPI:
  #   paths: ["/api/transactions/*"]
  manualTransactionsAPI:
    paths: ["/api/transactions/*"]
  accountsAPI:
    paths: ["/api/accounts/*"]
  budgetsAPI:
    paths: ["/api/budgets/*"]
  savingsAPI:
    paths: ["/api/savings/*"]
  aiAdvisorAPI:
    paths: ["/api/ai-advisor/*"]

serviceEndpoints:
  authService:
    url: "${AUTH_SERVICE_URL}"
  # transactionsService:
  #   url: '${TRANSACTIONS_SERVICE_URL}'
  manualTransactionsService:
    url: "${MANUAL_TRANSACTIONS_SERVICE_URL}"
  budgetSavingsService:
    url: "${BUDGET_SAVINGS_SERVICE_URL}"
  aiAdvisorService:
    url: "${AI_ADVISOR_SERVICE_URL}"

policies:
  - cors
  - jwt
  - proxy

pipelines:
  authPipeline:
    apiEndpoints: [authAPI]
    policies:
      - cors: {}
      - proxy:
          action:
            serviceEndpoint: authService

  usersPipeline:
    apiEndpoints: [usersAPI]
    policies:
      - cors: {}
      - jwt:
          action:
            secretOrPublicKey: "${JWT_SECRET}"
            credentialsRequired: true # require login
            algorithms: ["HS256"]
            checkCredentialExistence: false # still skip Consumer
      - proxy:
          action:
            serviceEndpoint: authService

  # transactionsPipeline:
  #   apiEndpoints: [transactionsAPI]
  #   policies:
  #     - cors: {}
  #     - jwt:
  #         action:
  #           secretOrPublicKey: "${JWT_SECRET}"
  #           credentialsRequired: true # protect tx endpoints
  #           algorithms: ["HS256"]
  #           checkCredentialExistence: false # uncontrolled mode
  #     - proxy:
  #         action:
  #           serviceEndpoint: transactionsService

  manualTransactionsPipeline:
    apiEndpoints: [manualTransactionsAPI]
    policies:
      - cors: {}
      - jwt:
          action:
            secretOrPublicKey: "${JWT_SECRET}"
            credentialsRequired: true # protect tx endpoints
            algorithms: ["HS256"]
            checkCredentialExistence: false # uncontrolled mode
      - proxy:
          action:
            serviceEndpoint: manualTransactionsService
  
  accountPipeline:
    apiEndpoints: [accountsAPI]
    policies:
      - cors: {}
      - jwt:
          action:
            secretOrPublicKey: "${JWT_SECRET}"
            credentialsRequired: true # protect tx endpoints
            algorithms: ["HS256"]
            checkCredentialExistence: false # uncontrolled mode
      - proxy:
          action:
            serviceEndpoint: manualTransactionsService

  budgetsPipeline:
    apiEndpoints: [budgetsAPI]
    policies:
      - cors: {}
      - jwt:
          action:
            secretOrPublicKey: "${JWT_SECRET}"
            credentialsRequired: true # protect tx endpoints
            algorithms: ["HS256"]
            checkCredentialExistence: false # uncontrolled mode
      - proxy:
          action:
            serviceEndpoint: budgetSavingsService

  savingsPipeline:
    apiEndpoints: [savingsAPI]
    policies:
      - cors: {}
      - jwt:
          action:
            secretOrPublicKey: "${JWT_SECRET}"
            credentialsRequired: true # protect tx endpoints
            algorithms: ["HS256"]
            checkCredentialExistence: false # uncontrolled mode
      - proxy:
          action:
            serviceEndpoint: budgetSavingsService

  aiAdvisorPipeline:
    apiEndpoints: [aiAdvisorAPI]
    policies:
      - cors: {}
      - jwt:
          action:
            secretOrPublicKey: "${JWT_SECRET}"
            credentialsRequired: true # protect tx endpoints
            algorithms: ["HS256"]
            checkCredentialExistence: false # uncontrolled mode
      - proxy:
          action:
            serviceEndpoint: aiAdvisorService